# Path related
dataset_path: data/raw/data.csv
kamus_path: data/raw/new_kamusalay.csv
dataset_cleaned_path: data/processed/raw_dataset.pkl
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl
train_feng_set_path:
- data/processed/x_train_feng.pkl
- data/processed/y_train_feng.pkl
valid_feng_set_path:
- data/processed/x_valid_feng.pkl
- data/processed/y_valid_feng.pkl
test_feng_set_path:
- data/processed/x_test_feng.pkl
- data/processed/y_test_feng.pkl
production_model_path: models/production_model.pkl
ohe_stasiun_path: models/ohe_stasiun.pkl
le_encoder_path: models/le_encoder.pkl
training_log_path: log/training_log.json

# Debug related
print_debug: true

# Columns by data type related
float_columns:
- Air temperature [K]
- Process temperature [K]
- Torque [Nm]

int_columns:
- Rotational speed [rpm]
- Tool wear [min]
- Target

category_columns:
- Type

# Predictors and label related
label: Target
predictors:
- Type
- Air temperature [K]
- Process temperature [K]
- Rotational speed [rpm]
- Torque [Nm]
- Tool wear [min]

# Range of data related
range_air_temperature:
- -40
- 125
range_process_temperature:
- 0
- 100
range_rotational_speed:
- 300
- 1250
range_torque:
- 0
- 65535
range_tool_wear:
- 0
- 65535
range_target:
- 0
- 1

# Splitting related
test_size: 0.2
valid_size: 0.5